version: "3.7"

services:
  app:
    image: ghcr.io/moltbot/moltbot:main
    restart: unless-stopped
    environment:
      CLAWDBOT_GATEWAY_TOKEN: "DEIN_LANGES_TOKEN"
    command: >
      node dist/index.js gateway
      --bind loopback
      --port 18789
      --allow-unconfigured
    volumes:
      - ${APP_DATA_DIR}/clawd:/home/node/clawd
